#!/usr/bin/env python

import sys
import itertools

if not len(sys.argv) == 3:
    raise SystemExit("usage: common-prefix old.gz new.gz")

with open(sys.argv[1], "rb") as old:
    with open(sys.argv[2], "rb") as new:
        for i in itertools.count():
            _old, _new = old.read(1000), new.read(1000)
            if _old == _new:
                continue
            for j in range(1000):
                if len(_old) <= j:
                    print(f"{sys.argv[1]} is a subset of {sys.argv[2]}")
                    sys.exit(0)
                if _old[j] != _new[j]:
                    raise SystemExit(f"Files differ at byte {i * 1000 + j}")
