on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14-dev
      - run: pip install . -r tests/requirements.txt pytest-cov
      - run: rm -rf sprat
        shell: bash
      - run: pytest --cov

  old-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run -v "$(pwd):/io" -t -e FORCE_COLOR=1 python:3.7-alpine \
          sh -c "cd /io && pip install . -r tests/requirements.txt pytest-cov && pytest"
